sudo: required
os: linux
dist: trusty
language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - sudo apt-get install -y apache2
  - sudo apt-get install -y php5-common libapache2-mod-php5 php5-cli
  - sudo service apache2 restart
  - sudo mkdir /var/www/angularjs-vulnerable
  - sudo cp test/vulnerable-sites/* /var/www/angularjs-vulnerable/
  - sudo chown -R www-data:www-data /var/www
  - sudo chmod +x test/test-vulnerable-sites.sh
  - pip install -r requirements.txt
  - cd /var/www
  - ls
  - cd /var/www/angularjs-vulnerable
  - ls
  - sudo wget -O 0.txt http://localhost/
  - sudo cat 0.txt
  - sudo wget -O 1.txt http://localhost/angularjs-vulnerable
  - sudo cat 1.txt
  - sudo wget -O 2.txt http://localhost/angularjs-vulnerable/angular-1.0.0.php
  - sudo cat 2.txt

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - python setup.py install
  - test/test-vulnerable-sites.sh