sudo: required
os: linux
language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - sudo apt-get install -y apache2
  - sudo apt-get install -y php5-common libapache2-mod-php5 php5-cli
  - sudo service apache2 restart
  - sudo mkdir /var/www/vulnerable-sites
  - sudo mv test/vulnerable-sites/* /var/www/vulnerable-sites
  - sudo chown -R www-data:www-data /var/www
  - sudo chmod +x test/test-vulnerable-sites.sh
  - pip install -r requirements.txt

script:
  - python setup.py install
  - test/test-vulnerable-sites.sh