sudo: required
os: linux
language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - sudo apt-get install -y apache2
  - sudo apt-get install -y php5-common libapache2-mod-php5 php5-cli
  - sudo service apache2 restart
  - cp -R test/vulnerable-sites /var/www/html/vulnerable-sites/
  - pip install -r requirements.txt

script:
  - python setup.py install
  - test/test-vulnerable-sites.sh